#pragma once

#include "common/types.h"

namespace Shader::Gcn {

// These structure definitions can be found in
// Radeon Sea Islands 3D/Compute
// Register Reference Guide

// Note:
// The code is auto-generated using SpiShaderRegMacroToStruct.py
// Do not edit this file manually,
// if there are something wrong, fix the script file instead.

struct SPI_SHADER_PGM_RSRC3_PS {
    u32 cu_en : 16;
    u32 wave_limit : 6;
    u32 lock_low_threshold : 4;
    u32 simd_disable : 4;
    u32 reserved : 2;
};

struct SPI_SHADER_PGM_LO_PS {
    u32 mem_base;
};

struct SPI_SHADER_PGM_HI_PS {
    u32 mem_base : 8;
    u32 reserved : 24;
};

struct SPI_SHADER_PGM_RSRC1_PS {
    u32 vgprs : 6;
    u32 sgprs : 4;
    u32 priority : 2;
    u32 float_mode : 8;
    u32 priv : 1;
    u32 dx10_clamp : 1;
    u32 debug_mode : 1;
    u32 ieee_mode : 1;
    u32 cu_group_disable : 1;
    u32 cdbg_user : 1;
    u32 fp16_ovfl : 1;
    u32 reserved : 5;
};

struct SPI_SHADER_PGM_RSRC2_PS {
    u32 scratch_en : 1;
    u32 user_sgpr : 5;
    u32 trap_present : 1;
    u32 wave_cnt_en : 1;
    u32 extra_lds_size : 8;
    u32 excp_en : 9;
    u32 load_collision_waveid : 1;
    u32 load_intrawave_collision : 1;
    u32 skip_usgpr0 : 1;
    u32 user_sgpr_msb : 1;
    u32 reserved : 3;
};

struct SPI_PS_INPUT_ENA {
    u32 persp_sample_ena : 1;
    u32 persp_center_ena : 1;
    u32 persp_centroid_ena : 1;
    u32 persp_pull_model_ena : 1;
    u32 linear_sample_ena : 1;
    u32 linear_center_ena : 1;
    u32 linear_centroid_ena : 1;
    u32 line_stipple_tex_ena : 1;
    u32 pos_x_float_ena : 1;
    u32 pos_y_float_ena : 1;
    u32 pos_z_float_ena : 1;
    u32 pos_w_float_ena : 1;
    u32 front_face_ena : 1;
    u32 ancillary_ena : 1;
    u32 sample_coverage_ena : 1;
    u32 pos_fixed_pt_ena : 1;
    u32 reserved : 16;
};

struct SPI_PS_INPUT_ADDR {
    u32 persp_sample_ena : 1;
    u32 persp_center_ena : 1;
    u32 persp_centroid_ena : 1;
    u32 persp_pull_model_ena : 1;
    u32 linear_sample_ena : 1;
    u32 linear_center_ena : 1;
    u32 linear_centroid_ena : 1;
    u32 line_stipple_tex_ena : 1;
    u32 pos_x_float_ena : 1;
    u32 pos_y_float_ena : 1;
    u32 pos_z_float_ena : 1;
    u32 pos_w_float_ena : 1;
    u32 front_face_ena : 1;
    u32 ancillary_ena : 1;
    u32 sample_coverage_ena : 1;
    u32 pos_fixed_pt_ena : 1;
    u32 reserved : 16;
};

struct SPI_SHADER_PGM_RSRC3_VS {
    u32 cu_en : 16;
    u32 wave_limit : 6;
    u32 lock_low_threshold : 4;
    u32 simd_disable : 4;
    u32 reserved : 2;
};

struct SPI_SHADER_PGM_LO_VS {
    u32 mem_base;
};

struct SPI_SHADER_PGM_HI_VS {
    u32 mem_base : 8;
    u32 reserved : 24;
};

struct SPI_SHADER_PGM_RSRC1_VS {
    u32 vgprs : 6;
    u32 sgprs : 4;
    u32 priority : 2;
    u32 float_mode : 8;
    u32 priv : 1;
    u32 dx10_clamp : 1;
    u32 debug_mode : 1;
    u32 ieee_mode : 1;
    u32 vgpr_comp_cnt : 2;
    u32 cu_group_enable : 1;
    u32 cdbg_user : 1;
    u32 fp16_ovfl : 1;
    u32 reserved : 3;
};

struct SPI_SHADER_PGM_RSRC2_VS {
    u32 scratch_en : 1;
    u32 user_sgpr : 5;
    u32 trap_present : 1;
    u32 oc_lds_en : 1;
    u32 so_base0_en : 1;
    u32 so_base1_en : 1;
    u32 so_base2_en : 1;
    u32 so_base3_en : 1;
    u32 so_en : 1;
    u32 excp_en : 9;
    u32 pc_base_en : 1;
    u32 dispatch_draw_en : 1;
    u32 skip_usgpr0 : 1;
    u32 user_sgpr_msb : 1;
    u32 reserved : 6;
};

struct SPI_SHADER_PGM_RSRC2_GS_VS {
    u32 scratch_en : 1;
    u32 user_sgpr : 5;
    u32 trap_present : 1;
    u32 excp_en : 9;
    u32 vgpr_comp_cnt : 2;
    u32 oc_lds_en : 1;
    u32 lds_size : 8;
    u32 skip_usgpr0 : 1;
    u32 user_sgpr_msb : 1;
    u32 reserved : 3;
};

struct SPI_SHADER_PGM_RSRC4_GS {
    u32 group_fifo_depth : 7;
    u32 spi_shader_late_alloc_gs : 7;
    u32 reserved : 18;
};

struct SPI_SHADER_PGM_LO_ES {
    u32 mem_base;
};

struct SPI_SHADER_PGM_HI_ES {
    u32 mem_base : 8;
    u32 reserved : 24;
};

struct SPI_SHADER_PGM_RSRC3_GS {
    u32 cu_en : 16;
    u32 wave_limit : 6;
    u32 lock_low_threshold : 4;
    u32 simd_disable : 4;
    u32 reserved : 2;
};

struct SPI_SHADER_PGM_LO_GS {
    u32 mem_base;
};

struct SPI_SHADER_PGM_HI_GS {
    u32 mem_base : 8;
    u32 reserved : 24;
};

struct SPI_SHADER_PGM_RSRC1_GS {
    u32 vgprs : 6;
    u32 sgprs : 4;
    u32 priority : 2;
    u32 float_mode : 8;
    u32 priv : 1;
    u32 dx10_clamp : 1;
    u32 debug_mode : 1;
    u32 ieee_mode : 1;
    u32 cu_group_enable : 1;
    u32 cdbg_user : 1;
    u32 gs_vgpr_comp_cnt : 2;
    u32 fp16_ovfl : 1;
    u32 reserved : 3;
};

struct SPI_SHADER_PGM_RSRC2_GS {
    u32 scratch_en : 1;
    u32 user_sgpr : 5;
    u32 trap_present : 1;
    u32 excp_en : 9;
    u32 es_vgpr_comp_cnt : 2;
    u32 oc_lds_en : 1;
    u32 lds_size : 8;
    u32 skip_usgpr0 : 1;
    u32 user_sgpr_msb : 1;
    u32 reserved : 3;
};

struct SPI_SHADER_PGM_RSRC4_HS {
    u32 group_fifo_depth : 7;
    u32 reserved : 25;
};

struct SPI_SHADER_PGM_LO_LS {
    u32 mem_base;
};

struct SPI_SHADER_PGM_HI_LS {
    u32 mem_base : 8;
    u32 reserved : 24;
};

struct SPI_SHADER_PGM_RSRC3_HS {
    u32 wave_limit : 6;
    u32 lock_low_threshold : 4;
    u32 simd_disable : 4;
    u32 cu_en : 16;
    u32 reserved : 2;
};

struct SPI_SHADER_PGM_LO_HS {
    u32 mem_base;
};

struct SPI_SHADER_PGM_HI_HS {
    u32 mem_base : 8;
    u32 reserved : 24;
};

struct SPI_SHADER_PGM_RSRC1_HS {
    u32 vgprs : 6;
    u32 sgprs : 4;
    u32 priority : 2;
    u32 float_mode : 8;
    u32 priv : 1;
    u32 dx10_clamp : 1;
    u32 debug_mode : 1;
    u32 ieee_mode : 1;
    u32 cdbg_user : 1;
    u32 ls_vgpr_comp_cnt : 2;
    u32 fp16_ovfl : 1;
    u32 reserved : 4;
};

struct SPI_SHADER_PGM_RSRC2_HS {
    u32 scratch_en : 1;
    u32 user_sgpr : 5;
    u32 trap_present : 1;
    u32 excp_en : 9;
    u32 lds_size : 9;
    u32 skip_usgpr0 : 1;
    u32 user_sgpr_msb : 1;
    u32 reserved : 5;
};

struct COMPUTE_PGM_LO {
    u32 data;
};

struct COMPUTE_PGM_HI {
    u32 data : 8;
    u32 reserved : 24;
};

struct COMPUTE_PGM_RSRC1 {
    u32 vgprs : 6;
    u32 sgprs : 4;
    u32 priority : 2;
    u32 float_mode : 8;
    u32 priv : 1;
    u32 dx10_clamp : 1;
    u32 debug_mode : 1;
    u32 ieee_mode : 1;
    u32 bulky : 1;
    u32 cdbg_user : 1;
    u32 fp16_ovfl : 1;
    u32 reserved : 5;
};

struct COMPUTE_PGM_RSRC2 {
    u32 scratch_en : 1;
    u32 user_sgpr : 5;
    u32 trap_present : 1;
    u32 tgid_x_en : 1;
    u32 tgid_y_en : 1;
    u32 tgid_z_en : 1;
    u32 tg_size_en : 1;
    u32 tidig_comp_cnt : 2;
    u32 excp_en_msb : 2;
    u32 lds_size : 9;
    u32 excp_en : 7;
    u32 skip_usgpr0 : 1;
};
} // namespace Shader::Gcn
